
.. _services-common:


Common Services
---------------

This section goes elaborates on the architecture, design, and specifications of
the observatory common services.

.. include:: services-engineering_UI.rst.inc

.. include:: services-command_execution.rst.inc

.. include:: services-system_supervisor.rst.inc

.. include:: services-telemetry.rst.inc

.. include:: services-alarm.rst.inc

.. include:: services-logging.rst.inc

.. include:: services-networking_infrastructure.rst.inc

.. include:: services-configuration.rst.inc


*On-Line Documentation Service*
...............................

  **To Be Added**

