.. _definitions:

Definitions and Acronyms
------------------------

+---------------------------+-------------------------------------------------------------------------+
| | Phrase / Acronym        | | Description                                                           |
+===========================+=========================================================================+
| | Actuator                | | Technical system or device which converts commands from the           |
| |                         | | controller into physical effects on the controlled plant.             |
+---------------------------+-------------------------------------------------------------------------+
| | AIT                     | | Assembly, Integration, and Testing                                    |
+---------------------------+-------------------------------------------------------------------------+
| | Controller              | | Control component designed to give the controlled plant a specified   |
| |                         | | control performance. The controller interacts with the controlled     |
| |                         | | plant through sensors and actuators. In its most feneral form, a      |
| |                         | | controller can include hardware, software, and human operations.      |
| |                         | | Its implementation can be distributed between the telescope and       |
| |                         | | operations domains.                                                   |
+---------------------------+-------------------------------------------------------------------------+
| | Control objective       | | The goal that the controlled system is supposed to achieve.           |
+---------------------------+-------------------------------------------------------------------------+
| | Control performance     | | Quantified capabilities of a controlled system                        |
+---------------------------+-------------------------------------------------------------------------+
| | Control System (CS)     | | Part of a controlled system which is designed to five the controlled  |
| |                         | | plant the specified control objectives.                               |
+---------------------------+-------------------------------------------------------------------------+
| | Controlled Plant (CP)   | | Physical system, or one of its parts, which is the target of the      |
| |                         | | control problem. Includes sensors and actuators.                      |
+---------------------------+-------------------------------------------------------------------------+
| | Controlled Subsystem    | | Control relevant part of a system to achieve the specified control    |
| |                         | | objectives. This includes the control system and the controlled       |
| |                         | | plant.                                                                |
+---------------------------+-------------------------------------------------------------------------+
| | Device                  | | The basic building block of a Controlled Plant including sensors      |
| |                         | | and actuators                                                         |
+---------------------------+-------------------------------------------------------------------------+
| | CP                      | | Controlled Plant                                                      |
+---------------------------+-------------------------------------------------------------------------+
| | CSS                     | | Controlled Subsystem                                                  |
+---------------------------+-------------------------------------------------------------------------+
| | DOSP                    | | Device Operation Support Package                                      |
+---------------------------+-------------------------------------------------------------------------+
| | DCS                     | | Device Control Subsystem                                              |
+---------------------------+-------------------------------------------------------------------------+
| | DCP                     | | Device Control Package                                                |
+---------------------------+-------------------------------------------------------------------------+
| | GMF                     | | GMT Modeling Framework                                                |
+---------------------------+-------------------------------------------------------------------------+
| | GMT                     | | Giant Magellan Telescope                                              |
+---------------------------+-------------------------------------------------------------------------+
| | GMTO                    | | Giant Magellan Telescope Organization                                 |
+---------------------------+-------------------------------------------------------------------------+
| | GSCH                    | | GMT Software and Controls Handbook                                    |
+---------------------------+-------------------------------------------------------------------------+
| | GCS                     | | GMT SWC Core Systems                                                  |
+---------------------------+-------------------------------------------------------------------------+
| | GCS_sim                 | | GMT SWC Core Systems lite version                                     |
+---------------------------+-------------------------------------------------------------------------+
| | FAT                     | | Factory Acceptance Testing                                            |
+---------------------------+-------------------------------------------------------------------------+
| | I/O                     | | Input/Output                                                          |
+---------------------------+-------------------------------------------------------------------------+
| | SWCS                    | | Software and Controls System                                          |
+---------------------------+-------------------------------------------------------------------------+
| | SLPDR                   | | System Level Preliminary Design Review                                |
+---------------------------+-------------------------------------------------------------------------+
| | PO                      | | Project Office                                                        |
+---------------------------+-------------------------------------------------------------------------+
| | SAT                     | | Site Acceptance Testing                                               |
+---------------------------+-------------------------------------------------------------------------+
| | SBS                     | | Sequence Based Specification                                          |
+---------------------------+-------------------------------------------------------------------------+
| | Sensor                  | | Device that measures states of the controlled plant and provides      |
| |                         | | them as feedback inputs to the controller                             |
+---------------------------+-------------------------------------------------------------------------+
| | SOW                     | | Statement of Work                                                     |
+---------------------------+-------------------------------------------------------------------------+
| | State                   | | Set of variables or parameters describing the dyanmic behavior of     |
| |                         | | the controlled system at a given time                                 |
+---------------------------+-------------------------------------------------------------------------+
| | TBD                     | | To Be Determined                                                      |
+---------------------------+-------------------------------------------------------------------------+


