
enum class OperationalState : std::uint8_t { INITIAL=0, TERMINAL=1, PREVIOUS=2, OFF=3, STARTING=4, ON=5, INITIALIZING=6, RUNNING=7, IDLE=8, DISABLED=9, HALTING=10, SHUTTING_DOWN=11, FAULT=12, RESETTING=13 };
MSGPACK_ADD_ENUM(OperationalState)

