.. _terminology:

Terminology
-----------

The following diagram describes the control engineering terminology used in this
document. The terminology is based on the ECSS-E-60-A - Control Engineering
standard. As shown in the Figure below, in the case of GMT DCS subsystems, the
Controlled Plant or system under control, includes also the Sensors and
Actuators of the system.


.. figure:: _static/general_control_structure.png

   General Control Structure

