#
# GMT Software and Controls documentation build configuration file, created by
# sphinx-quickstart on Wed Jun  5 14:48:12 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

project = 'GMT Software And Controls'
copyright = '2024, contributors'
version = '1.14'
release = '1.14'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx_copybutton',
]

templates_path = ['_templates']
exclude_patterns = ['**/*_inc.rst']
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'furo'
html_static_path = ['_static']
html_title = 'GMT Software And Controls'
html_short_title = 'Home'
html_favicon = '_static/favicon.ico'

html_theme_options = {
    'light_logo': 'logoblue.png',
    'dark_logo': 'logowhite.png',
}

numfig = True
numfig_secnum_depth = 1


# -- Options for ePub output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-epub-output
epub_title = 'GMT Software and Controls'
epub_author = 'GMT SWC'
epub_publisher = 'GMT SWC'
epub_copyright = '2024, GMT SWC'

# -- Options for LaTeX output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-latex-output

latex_engine = 'xelatex'
latex_elements = {
  'classoptions': ',openany,oneside',
  'babel':        '\\usepackage[english]{babel}',
  'pointsize':    '9pt',
  'preamble': '\n%Added from template'
              '\n\\setcounter{tocdepth}{2}'
              '\n\\setcounter{secnumdepth}{3}'
              '\n\\usepackage{fancyheadings}'
              '\n\\usepackage{tocloft}'
              '\n\\setlength{\\cftfignumwidth}{2em}'
              '\n\\setlength{\\cfttabnumwidth}{3em}'
              '\n\\fancypagestyle{wholedocument}{\\fancyhead{}\\fancyfoot{}\\renewcommand{\\headrulewidth}{0.4pt}'
              '\n\\renewcommand{\\footrulewidth}{0.4pt}'
              '\n\\fancyhead[R]{\\color{black} \\bfseries  \\fontfamily{phv}}'
              '\n\\fancyfoot[L]{\\color{black} \\bfseries  \\small {\\rightmark}}'
              '\n\\fancyfoot[R]{\\color{black} {\\bfseries \\thepage}}}'
              '\n\\renewcommand{\\chaptermark}[1]{\\markboth{\\thechapter.#1}{}}'
              '\n\\renewcommand{\\sectionmark}[1]{\\markright{\\thesection.#1}{}}'
              '\n\\renewcommand{\\thepage}{\\roman{page}}'
              '\n\\pagestyle{wholedocument}'
              '\n\\clearpage'
              '\n\\setcounter{page}{1}'
              '\n\\pagenumbering{arabic}'
              '\n%Added from template'
}

# (startdocname, targetname, title, author, theme, toctree_only)
latex_common = ('Software and Controls Group', 'manual')
latex_documents = [
  ('software_development/installation',                                'swc_installation.tex',             'SDK Installation', *latex_common),
  ('software_development/core_services_user_guide',                    'swc_core_services_user_guide.tex', 'Core Services user guide', *latex_common),
  ('software_development/gds_guide',                                   'swc_gds_documentation.tex',        'gds documentation', *latex_common),
  ('software_development/modeling_guidelines',                         'swc_modeling_guidelines.tex',      'Model specification guide document', *latex_common),
  ('software_development/model_language_mapping/mapping_model_to_cpp', 'swc_map_model_cpp.tex',            'Mapping between the Model Definition Files and C++ source code', *latex_common),
  ('software_development/isample_example',                             'swc_isample_example.tex',          'ISample example', *latex_common),
  ('software_development/hdk_example',                                 'swc_hdk_example.tex',              'HDK example', *latex_common),
  ('software_development/test_guidelines',                             'swc_test_guidelines.tex',          'OCS Test Guidelines', *latex_common),
  ('software_development/ui_fwk',                                      'swc_ui_fwk_guidelines.tex',        'UI Framework Guidelines', *latex_common),
  ('software_development/grs_guide',                                   'swc_grs_documentation.tex',        'grs documentation', *latex_common),
]
